version: '3'
services:
  prisma:
    image: prismagraphql/prisma:${PRISMA_VERSION}
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: mysql-db
            port: ${DB_PORT}
            user: ${DB_USERNAME}
            password: ${DB_PASSWORD}
            
  mysql-db:
    image: mysql:5.7
    ports:
    - "${DB_PORT}:3306"
    restart: always
    command: mysqld
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - mysql:/var/lib/mysql
      
volumes:
  mysql: ~
    
  